name: healing_neko
description: "Meow meow"
publish_to: 'none'
version: 0.0.5+5

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  flutter_lints: ^5.0.0
  flutter_vibrate: ^1.3.0
  particles_flutter: ^1.0.1
  url_launcher: ^6.1.12
  shared_preferences: ^2.1.1
  window_manager: ^0.4.3
  vibration: ^2.0.1
  back_button_interceptor: ^8.0.0
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.2
  flagsmith: ^6.0.0
  salomon_bottom_bar: ^3.3.2
  awesome_snackbar_content: ^0.1.3
  loading_indicator: ^3.1.1
  flutter_gravatar: ^2.0.2
  http: ^1.2.0
  zxing_lib: ^1.1.2
  bottom_sheet: ^4.0.1
  toastification: ^2.3.0
  flutter_statusbarcolor_ns: ^0.6.0
  audioplayers: ^6.1.0
  flutter_local_notifications: ^18.0.1
  package_info_plus: ^8.1.1
  flutter_markdown: ^0.7.3
  device_info_plus: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/ui/
    - assets/nekos/
    - assets/soundscapes/
    - assets/neko/
    - soundscapes.md
    - README.md    
    - changes.md   
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
