name: healing_neko
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_vibrate: ^1.3.0
  particles_flutter: "^0.1.1"
  url_launcher: ^6.1.12
  shared_preferences: ^2.1.1
  window_manager: ^0.3.4
  vibration: ^1.7.5
  back_button_interceptor: ^7.0.0
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.2
  flagsmith: ^5.0.1
  salomon_bottom_bar: ^3.3.2
  awesome_snackbar_content: ^0.1.3
  loading_indicator: ^3.1.1
  flutter_gravatar: ^2.0.2
  qr_code_dart_scan: ^0.7.5
  http: ^1.2.0
  zxing_lib: ^1.1.2
  image: ^4.1.7
  camera_platform_interface: ^2.7.4
  camera: ^0.10.5+9
  qr_scanner_with_effect: ^1.0.5
  bottom_sheet: ^4.0.1
  toastification: ^1.2.1
  flutter_statusbarcolor_ns: ^0.5.0
  audioplayers: ^5.2.1
  flutter_local_notifications: ^17.0.0
  package_info_plus: ^5.0.1

flutter:
  uses-material-design: true
